on:
  push:
    branches:
      - staging
name: ğŸš€ Staging website on push
jobs:
  web-deploy:
    name: ğŸ‰ Staging
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.lpphotelyogya.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
